# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.3.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = "2"    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    bundle_install
    cocoapods
    increment_build_number
    gym(
      scheme: "PhotoStickers"
    )
    pilot(skip_waiting_for_build_processing: true)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    bundle_install
    cocoapods
    increment_build_number
    gym(
      scheme: "PhotoStickers"
    )
    deliver(force: true)
    # frameit
  end

  desc "Updates the storyboard identifier Swift values."
  lane :storyboard_ids do
    sh "cd .. ; bundle exec sbconstants ./Shared/StoryboardIdentifiers.swift --source-dir ./ --swift"
  end

  # You can define as many lanes as you want

  after_all do |lane|
    
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
