
devices([
  "iPhone SE",
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone XS",
  "iPhone XS Max",
  "iPad Pro (12.9-inch) (3rd generation)",
  "iPad Pro (9.7-inch)",
])

languages([
  "en-US",
  "de-DE",
])

scheme "PhotoStickers"
workspace "./PhotoStickers.xcworkspace"

clear_previous_screenshots false
reinstall_app true
localize_simulator true

#launch_arguments([]) # See https://github.com/fastlane/snapshot#launch-arguments
#output_simulator_logs false
#skip_open_summary false
#skip_helper_version_check false
#erase_simulator false
#clean false
#number_of_retries 1
#stop_after_first_error false
